= Integration with Keycloak 19+

More information is available in readme file for pax-web-keycloak18.

For Keycloak 19+, where the OSGi/Karaf/Pax Web bits are removed, we have to repackage more. For Keycloak 18 we had to repackage Jetty and Tomcat Keycloak libraries, for Keycloak 19+ we'll additionally repackage Undertow one.

The Keycloak libraries that were providing `org.ops4j.pax.web.service.AuthenticatorService` services in Keycloak 18 were:

* org.keycloak/keycloak-pax-web-jetty94
* org.keycloak/keycloak-pax-web-tomcat8
* org.keycloak/keycloak-pax-web-undertow

While the Undertow related library provided only `org.keycloak.adapters.osgi.tomcat.KeycloakAuthenticatorService`, Jetty and Tomcat related libraries were providing additionally:

* `org.keycloak.adapters.osgi.jetty94.PaxWebIntegrationService` - this was used to call Pax Web API methods:
** `org.ops4j.pax.web.service.WebContainer.registerJettyWebXml()`
** `org.ops4j.pax.web.service.WebContainer.registerConstraintMapping()`
** `org.ops4j.pax.web.service.WebContainer.registerLoginConfig()`
* `org.keycloak.adapters.osgi.undertow.PaxWebIntegrationService` - as above, but for Undertow
* `org.keycloak.adapters.osgi.undertow.CxfKeycloakAuthHandler` - implementation of `org.apache.cxf.transport.http_undertow.CXFUndertowHttpHandler` for `org.apache.cxf/cxf-rt-transports-http-undertow`

We don't backport the above to Pax Web for Keycloak 20+ support.

== Installation

The Keycloak integration tests can be performed using Apache Karaf 4.4.4.

Before starting Karaf:
----
$ cat <<EOF >>etc/config.properties
paxweb.authMethod = KEYCLOAK
paxweb.keycloak.resolver = org.keycloak.adapters.osgi.PathBasedKeycloakConfigResolver
EOF
----

Before trying to run the example, we need running Keycloak 20 server:
----
$ pwd
/data/servers/keycloak-20.0.4

$ bin/kc.sh start-dev --http-port 8180
...
2023-10-12 10:22:18,159 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
...
2023-10-12 10:22:27,105 INFO  [io.quarkus] (main) Keycloak 22.0.4 on JVM (powered by Quarkus 3.2.6.Final) started in 10.245s. Listening on: http://0.0.0.0:8180
...
----

Now, the Keycloak console is available at http://127.0.0.1:8180/admin/master/console/#/.

We need to prepare some configuration:

* separate realm called `paxweb`
* `paxweb-admin` and `paxweb-viewer` roles
* `admin` and `viewer` users (users' passwords must be set)
* `whiteboard-customcontext` _client_ with `http://localhost:8181/pax-web-security/*` _Valid Redirect URIs_
* `whiteboard-rootcontext` _client_ with `http://localhost:8181/*` _Valid Redirect URIs_

Make sure that _Standard Flow Enabled_ is selected for the clients.

For convenience, I've exported Pax Web Keycloak realm into `realm-export.json` file - it can be imported into fresh installation of Keycloak server. You should however create `admin` and `viewer` users and assign them `paxweb-admin` and `paxweb-viewer` roles respectively.

After configuring the realm, roles, users and the clients, we can get the configurations and write them to Karaf's:

`etc/whiteboard-customcontext-keycloak.json`:
----
{
  "realm": "paxweb",
  "auth-server-url": "http://127.0.0.1:8180/",
  "ssl-required": "external",
  "resource": "whiteboard-customcontext",
  "public-client": true,
  "confidential-port": 0
}
----

`etc/whiteboard-rootcontext-keycloak.json`:
----
{
  "realm": "paxweb",
  "auth-server-url": "http://127.0.0.1:8180/",
  "ssl-required": "external",
  "resource": "whiteboard-rootcontext",
  "public-client": true,
  "confidential-port": 0
}
----

If the resolver used is `org.keycloak.adapters.osgi.PathBasedKeycloakConfigResolver`, the configuration file for `/pax-web-security` context should be `etc/pax-web-security-keycloak.json`. This option is used to check different types of `org.keycloak.adapters.KeycloakConfigResolver` implementations.

Now we can install features in Karaf.

In Karaf for Jetty:
----
karaf@root()> feature:install pax-web-http-jetty
karaf@root()> feature:install pax-web-jsp
karaf@root()> feature:install pax-web-whiteboard
karaf@root()> feature:install pax-web-karaf
karaf@root()> feature:install pax-web-jetty-keycloak
karaf@root()> install -s mvn:org.ops4j.pax.web.samples/whiteboard-security/8.0.23
----

In Karaf for Tomcat:
----
karaf@root()> feature:install pax-web-http-tomcat
karaf@root()> feature:install pax-web-jsp
karaf@root()> feature:install pax-web-whiteboard
karaf@root()> feature:install pax-web-karaf
karaf@root()> feature:install pax-web-tomcat-keycloak
karaf@root()> install -s mvn:org.ops4j.pax.web.samples/whiteboard-security/8.0.23
----

In Karaf for Undertow:
----
karaf@root()> feature:install pax-web-http-undertow
karaf@root()> feature:install pax-web-jsp
karaf@root()> feature:install pax-web-whiteboard
karaf@root()> feature:install pax-web-karaf
karaf@root()> feature:install pax-web-undertow-keycloak
karaf@root()> install -s mvn:org.ops4j.pax.web.samples/whiteboard-security/8.0.23
----

Application can be tested by browsing to http://localhost:8181/app.
