
////

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	 
	    http://www.apache.org/licenses/LICENSE-2.0
	 
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

////

= Artifacts

[[Artifacts-pax-web-api]]
== pax-web-api

This artifact contains Pax Web API which are the classes that are added
in extension to standard HTTP
Service. This is the only artifact you should depend, at compile time,
if you are in need of Pax Web extensions.

[[Artifacts-pax-web-spi]]
== pax-web-spi

This artifact contains the interfaces that should be implemented by a
service provider wishing to provide an alternative implementation that
is not Jetty based. The Jetty artifact
implements this SPI in order to be used by Pax Web
Runtime.

[[Artifacts-pax-web-runtime]]
== pax-web-runtime

This artifact is the core of Pax Web (the engine if you like so). It
implements the API and will make use of an
SPI, such as
Jetty in order to fulfill is job.

[[Artifacts-pax-web-jsp]]
== pax-web-jsp

This artifact contains Pax Web JSP support based on Jasper. It is an
optional component that will be used by
runtime if present. If you do not use JSPs
in your project you can leave this artifact out of your deployment
setup.

[[Artifacts-pax-web-jetty]]
== pax-web-jetty

This artifact is the Jetty based implementation of
SPI. This artifact *does not include*
Jetty, so you will have to deploy Jetty along by yourself. The reason
behind not including Jetty is to allow you to make your choice about the
version of Jetty to be used, as for example, in case that a new version
of Jetty is available and you are in need to use it.

[[Artifacts-pax-web-jetty-bundle]]
== pax-web-jetty-bundle

This artifact is a convenience artifact that bundles together most of
the artifacts above plus a version of jetty. This in order to make your
deployment easier. It includes the following:
pax-web-api,
pax-web-spi,
pax-web-runtime,
pax-web-jetty and necessary jetty bundles.
Basically, if you deploy this bundle you are good to go without any
additional bundles (beside the jsp or extenders that you should deploy
as you need).

[[Artifacts-pax-web-extender-war]]
== pax-web-extender-war

This artifact is the implementation of
Pax Web WAR Extender and should be
included in case that you want to deploy WAR files into the OSGi
framework.

[[Artifacts-pax-web-extender-whiteboard]]
== pax-web-extender-whiteboard

This artifact is the implementation of
Pax Web Whiteboard Extender and
should be included if you wish to publish your web elements simply by
registering them as a service.

[[Artifacts-pax-web-resources]]
== pax-web-resources-api

Compile-only module for Servlet 3.0 resource-lookup.

== pax-web-resources-extender

This artifact is the default implementation of Pax Web Resources API.
It exports the api packages as well, so there is no need to deploy the api-bundle.

== pax-web-resources-jsf

This artifact provides a JSF-ResourceHandler which will lookup resources in other bundles
when they are not found within JSF-WAB.


