= Artifacts

This section describes the individual bundles and other artifacts provided by Pax Web 5.x.

[[Artifacts-pax-web-deployer]]
== pax-web-deployer

This artifact is an optional bundle which supports file system deployment of traditional
WARs without an OSGi manifest. This feature is based on Apache Felix File Install and the Pax URL
WAR protocol handler (more specifically, the `webbundle:` protocol).

[[Artifacts-pax-web-descriptor]]
== pax-web-descriptor

`pax-web-descriptor` contains a JAXB model of the `web.xml` deployment descriptor generated from
the corresponding XML schema. This model is used at run-time to unmarshal deployment descriptors
and to transport deployment metadata between Pax Web bundles.

[[Artifacts-pax-web-extender]]
== pax-web-extender

This artifact implements the OSGi extender pattern for web application bundles. In general,
an OSGi extender listens to bundle events and adds functionality to some of the observed bundles.

The `pax-web-extender` monitors web application bundles, identified by the `Web-ContextPath` manifest
header, parses their deployment metadata and deploys them to the servlet container.

[[Artifacts-pax-web-features]]
== pax-web-features

This artifact contains feature definitions to provision Pax Web in Apache Karaf 3.0.0 or higher.

[[Artifacts-pax-web-jaas]]
== pax-web-jaas

This artifact contains some helper classes to implement JAAS based login configurations for
web applications.

[[Artifacts-pax-web-jsp]]
== pax-web-jsp

This artifact contains JSP support based on Jasper and some other modules of Apache Tomcat 8.x. 
It is an optional component that will be used by the runtime if present. If you do not use JSPs
in your project, you can leave out this artifact from your
setup.

[[Artifacts-pax-web-spi]]
== pax-web-spi

This artifact contains some model classes and interfaces to be implemented for a specific
servlet container adapter. This service provider interface (SPI) currently has just one implementation
in `pax-web-undertow`. 


[[Artifacts-pax-web-undertow]]
== pax-web-undertow

This artifact implements the `pax-web-spi` service provider interface based on Undertow. It  
*does not include* Undertow, so you will have to provision Undertow separately.

Note that the official Undertow artifacts and their XNIO dependencies currently do not include
OSGi headers in their manifests.

For this reason, OPS4J provides OSGified versions of these artifacts in the Pax Tipi project.


