
////

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	 
	    http://www.apache.org/licenses/LICENSE-2.0
	 
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

////

= Basic Configuration


The following is a list with basic configuration properties that can be
used to customize Pax Web.

[[BasicConfiguration-org.osgi.service.http.port]]
`org.osgi.service.http.port`

This property specifies the port used for servlets and resources
accessible via HTTP. Default value for this property is 8080. +
 You can specify a value of 0 (zero), if you wish to allow Pax Web to
automatically determine a free port to use for HTTP access.

[[BasicConfiguration-org.osgi.service.http.port.secure]]
`org.osgi.service.http.port.secure`

This property specifies the port used for servlets and resources
accessible via HTTPS. Default value for this property is 8443. +
 You can specify a value of 0 (zero), if you wish to allow Pax Web to
automatically determine a free port to use for HTTPS access.

[[BasicConfiguration-org.osgi.service.http.enabled]]
`org.osgi.service.http.enabled`

This property specifies if the HTTP is enabled. If ``true'' the support
for HTTP access will be enabled. If ``false'' the support for HTTP
access will be disabled. Default value is ``true''.

[[BasicConfiguration-org.osgi.service.http.secure.enabled]]
`org.osgi.service.http.secure.enabled`

This property specifies if the HTTPS is enabled. If ``true'' the support
for HTTPS access will be enables. If ``false'' the support for HTTPS
access will be disabled. Default value is ``false''.

[[BasicConfiguration-org.osgi.service.http.useNIO]]
`org.osgi.service.http.useNIO`

This property specifies if the connections established use the nio
classes from java. If ``true'' connections are established using NIO, if
``false'' connections are established the standard way.

[[BasicConfiguration-javax.servlet.context.tempdir]]
`javax.servlet.context.tempdir`

A temporary directory that can be accessed via the servlet context
attribute with the same name. If not set a default temporary directory
wil be created and used.

[[BasicConfiguration-org.ops4j.pax.web.session.timeout]]
`org.ops4j.pax.web.session.timeout`

The number of minutes after which an inactive session will timeout.

[[BasicConfiguration-org.ops4j.pax.web.listening.addresses]]
`org.ops4j.pax.web.listening.addresses`

This property specifies the comma separated list of addresses used to
provide servlets and resources via HTTP +
 (e.g. localhost or localhost,10.0.0.1). Host names or IP addresses can
be used. Default value is ``0.0.0.0''.

[[BasicConfiguration-org.ops4j.pax.web.session.cookie]]
`org.ops4j.pax.web.session.cookie`

Session cookie name. +
 From Jetty documentation: +
 Defaults to JSESSIONID.

[[BasicConfiguration-org.ops4j.pax.web.session.url]]
`org.ops4j.pax.web.session.url`

Session URL. +
 From Jetty documentation: +
 Defaults to jsessionid. If set to null or ``none'' no URL rewriting
will be done

[[BasicConfiguration-org.ops4j.pax.web.worker.name]]
`org.ops4j.pax.web.worker.name`

Sets worker name for use with Apache mod_proxy_balancer sticky
sessions. +
 See: https://wiki.eclipse.org/Jetty/Howto/Configure_mod_proxy +
 Defaults to null.

[[BasicConfiguration-org.ops4j.pax.web.config.file]]
`org.ops4j.pax.web.config.file`

Configures where to look for an external configuration file for the
underlying web container (e.g. Jetty).

[[BasicConfiguration-org.ops4j.pax.web.log.ncsa.format]]
`org.ops4j.pax.web.log.ncsa.format`

Sets the format for logging access logs

-----------------------------------------------------------
org.ops4j.pax.web.log.ncsa.format = /yyyy_mm_dd.request.log
-----------------------------------------------------------

[[BasicConfiguration-org.ops4j.pax.web.log.ncsa.retainDays]]
`org.ops4j.pax.web.log.ncsa.retainDays`

------------------------------------------
org.ops4j.pax.web.log.ncsa.retainDays = 90
------------------------------------------

[[BasicConfiguration-org.ops4j.pax.web.log.ncsa.append]]
`org.ops4j.pax.web.log.ncsa.append`

----------------------------------------------
org.ops4j.pax.web.log.ncsa.append = true/false
----------------------------------------------

[[BasicConfiguration-org.ops4j.pax.web.log.ncsa.extended]]
`org.ops4j.pax.web.log.ncsa.extended`

------------------------------------------------
org.ops4j.pax.web.log.ncsa.extended = true/false
------------------------------------------------

[[BasicConfiguration-org.ops4j.pax.web.log.ncsa.LogTimeZone]]
`org.ops4j.pax.web.log.ncsa.LogTimeZone`

-------------------------------------------
org.ops4j.pax.web.log.ncsa.LogTimeZone= GMT
-------------------------------------------

[[BasicConfiguration-org.osgi.service.http.checkForwardedHeaders]]
`org.osgi.service.http.checkForwardedHeaders`

------------------------------------------------
org.osgi.service.http.checkForwardedHeaders = true/false
------------------------------------------------
Behind a reverse proxy it is sometime necessary to handle the X-Forwarded-*.
