
////

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	 
	    http://www.apache.org/licenses/LICENSE-2.0
	 
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

////

Build
=====

The following instructions are explaining how to build
Pax Web by using
http://maven.apache.org[Apache Maven]. You may also use another means
for building as for example your preferred IDE, since most IDE’s will
support Maven.

To build Pax Web follow this steps:

* Download and
http://maven.apache.org/download.html#Installation[install Apache Maven]
* Download the latest source from OPS4J Pax
Web GIT Repository
* In a terminal window go the the root folder where you have downloaded
the source and execute the following command:
+
-----------
mvn install
-----------
