= Configuration

== Overview

Pax Web can be configured using configuration properties provided by the OSGi Configuration Admin service,
as OSGi framework properties or as Java system properties.

There are two levels of configuration: per server and per deployment.

Per deployment configuration is only supported via Configuration Admin.

== Server-level Configuration Properties

[options="header"]
|===

| Property key | Default value  | Meaning

| org.ops4j.pax.web.hosts |  | Comma-separated list of virtual host names

| org.ops4j.pax.web.host.<hostname>.aliases |  | Comma-separated list of aliases for a virtual host

| org.ops4j.pax.web.ssl.keystore.type | JKS | SSL Keystore format

| org.ops4j.pax.web.ssl.password |  | Password for the keystore

| org.ops4j.pax.web.undertow.accesslog.format | common | Access log format

| org.ops4j.pax.web.undertow.accesslog.enabled  | false | Is the access log enabled?

| org.osgi.service.http.enabled | true | Is the HTTP protocol enabled?

| org.osgi.service.http.port | 8080 | HTTP port

| org.osgi.service.http.port.secure | 8443 | HTTPS port

| org.osgi.service.http.secure.enabled | false | Is the HTTPS protocol enabled?

|===


While looking for a configuration property, Pax Web will first use the
property configured via Configuration Admin. If the property is not found, it will look for a 
framework property with the same name, falling back to a system property of the same name.
If no property is defined, a default value is applied as indicated above.

The PID used for Configuration Admin  is `org.ops4j.pax.web.undertow`.

== Deployment-level Configuration Properties

Pax Web supports deployment-level configuration via Configuration Admin, letting the user override
the context path or assign the deployment to a given virtual host.

This mechanism is based on a factory configuration with PID `org.ops4j.pax.web.deployment`.

For each deployment, Pax Web applies a configuration of this PID where the property 
`bundle.symbolicName` matches the bundle symbolic name of the deployment or generates a default
configuration from the bundle manifest.

The following properties are supported:

[options="header"]
|===

| Property key | Default value  | Meaning

| bundle.symbolicName | Value of `Bundle-SymbolicName` manifest header | Used to assign a configuration to a given bundle

| contextPath | Value of `Web-ContextPath` manifest header | Overrides the web context path for the given deployment.

| virtual.host |  | Name of virtual host for this deployment. The host must be configured at server level.

|===
