
////

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	 
	    http://www.apache.org/licenses/LICENSE-2.0
	 
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

////

Pax Web Developer Guide
=======================
:toc-title: Pax Web Developer Guide

The following guides details different aspects of
Pax Web internals and are aimed towards
developers that wants to understand the inner workings of
Pax Web and/or develop/maintain current code
base of Pax Web and/or develop extensions in
top of Pax Web.
Details on Pax Web can be found at the link:index.html[overview].

// Push titles down one level
:leveloffset: +1

include::Source.adoc[]

include::Build.adoc[]

include::Artifacts.adoc[]

// Return to normal title levels
:leveloffset: -1
