
////

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	 
	    http://www.apache.org/licenses/LICENSE-2.0
	 
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

////

Error Pages
===========

[[ErrorPages-Registererrorpages]]
Register error pages
--------------------

*`public void registerErrorPage( String error, String location, HttpContext httpContext )`*

Registers an error page to customize the response sent back to the web
client in case that an exception or error propagates back to the web
container, or the servlet/filter calls sendError() on the response
object for a specific status code. +
 Read Servlet specs for details related to error pages.

[cols=",",]
|=======================================================================
|error |A fully qualified Exception class name or an error status code.
Cannot be null.

|location |The request path that will fill the response page. The
location must start with an ``/''. Cannot be null.

|httpContext |The http context this error page is for. If null a default
http context will be used.

|Throws |IllegalArgumentException — if: error is null or empty location
is null location does not start with a slash ``/''
|=======================================================================

[[ErrorPages-Unregistererrorpages]]
Unregister error pages
----------------------

*`public void unregisterErrorPage( String error, HttpContext httpContext )`*

Unregisters a previous registered error page.

[cols=",",]
|=======================================================================
|error |A fully qualified Exception class name or an error status code
to be unregistered. Cannot be null.

|httpContext |The http context from which the error page should be
unregistered. Cannot be null.

|Throws |IllegalArgumentException — if: error is null or empty error
page was not registered before httpContext is null
|=======================================================================
