
////

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	 
	    http://www.apache.org/licenses/LICENSE-2.0
	 
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

////

= Installing using Karaf-features

Pax Web provides a set of feature-descriptors for
http://karaf.apache.org/[Apache Karaf] for convenient installation. To
enable these features, add them in Karaf using the following command:

[listing,subs="+attributes"]
features:addurl mvn:org.ops4j.pax.web/pax-web-features/{docVersion}/xml/features

When you type `features:list` now, you will see the following features
available:

[listing,subs="+attributes"]
----
State         Version           Name                          Repository              Description
[uninstalled] [{docVersion}] pax-jetty                     org.ops4j.pax.web-{docVersion} Provide Jetty engine support
[uninstalled] [{docVersion}] pax-http                      org.ops4j.pax.web-{docVersion} Implementation of the OSGI HTTP Service
[uninstalled] [{docVersion}] pax-http-whiteboard           org.ops4j.pax.web-{docVersion} Provide HTTP Whiteboard pattern support
[uninstalled] [{docVersion}] pax-war                       org.ops4j.pax.web-{docVersion} Provide support of a full WebContainer
----

You can now install each of these features using `features:install`.
