
////

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	 
	    http://www.apache.org/licenses/LICENSE-2.0
	 
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

////

JSP Configuration
=================

The following is a list with extra configuration properties for JSP
compilation, these can be used to customize Pax Web. If not specified
otherwise, the property is available since
Pax Web - 1.0.0. +
 These properties are send to the underlying JSP servlet Container
https://www.eclipse.org/jetty/documentation/current/configuring-jsp.html[see]

The default configuration used can be seen via the MetaTypeService or in
the metatype.xml of the runtime bundle.

[[JSPConfiguration-org.ops4j.pax.web.jsp.scratch.dir]]
`org.ops4j.pax.web.jsp.scratch.dir`

This property defines the Directory where servlets are generated.

[[JSPConfiguration-org.ops4j.pax.web.jsp.check.interval]]
`org.ops4j.pax.web.jsp.check.interval`

Interval in seconds between background recompile checks. Only relevant
if org.ops4j.pax.web.jsp.development=false.

[[JSPConfiguration-org.ops4j.pax.web.jsp.debug.info]]
`org.ops4j.pax.web.jsp.debug.info`

Include debugging info in class file.

[[JSPConfiguration-org.ops4j.pax.web.jsp.development]]
`org.ops4j.pax.web.jsp.development`

If true, recompilation checks are made on each request.

[[JSPConfiguration-org.ops4j.pax.web.jsp.enable.pooling]]
`org.ops4j.pax.web.jsp.enable.pooling`

Determines whether tag handler pooling is enabled.

[[JSPConfiguration-org.ops4j.pax.web.jsp.ie.classid]]
`org.ops4j.pax.web.jsp.ie.classid`

Classid used for InternetExplorer

[[JSPConfiguration-org.ops4j.pax.web.jsp.java.encoding]]
`org.ops4j.pax.web.jsp.java.encoding`

Pass through the encoding to use for the compilation.

[[JSPConfiguration-org.ops4j.pax.web.jsp.keep.generated]]
`org.ops4j.pax.web.jsp.keep.generated`

Do you want to keep the generated Java files around?

[[JSPConfiguration-org.ops4j.pax.web.jsp.log.verbosity.level]]
`org.ops4j.pax.web.jsp.log.verbosity.level`

Log verbosity level used.

[[JSPConfiguration-org.ops4j.pax.web.jsp.mapped.file]]
`org.ops4j.pax.web.jsp.mapped.file`

Support for mapped Files. Generates a servlet that has a print statement
per line of the jsp file.

[[JSPConfiguration-org.ops4j.pax.web.jsp.tagpool.max.size]]
`org.ops4j.pax.web.jsp.tagpool.max.size`

Maximum size for tags in pool.

[[JSPConfiguration-org.ops4j.pax.web.jsp.precompilation]]
`org.ops4j.pax.web.jsp.precompilation`

If JSPs should be precompiled (see for more details
http://team.ops4j.org/browse/PAXWEB-370[here])


NOTE: Since Pax Web - 2.0.0
