
////

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	 
	    http://www.apache.org/licenses/LICENSE-2.0
	 
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

////

JSP
===

Pax Web has support for Java Server Pages
(JSP) via using
http://tomcat.apache.org/tomcat-6.0-doc/jasper-howto.html[Tomcat Jasper
2]

[[JSP-Why]]
Why
---

Quoted from http://java.sun.com/products/jsp/[Java Server Pages home
page]:

______________________________________________________________________________________________________________________________________________________________________________________________________________
JavaServer Pages (JSP) technology provides a simplified, fast way to
create dynamic web content. JSP technology enables rapid development of
web-based applications that are server- and platform-independent.
______________________________________________________________________________________________________________________________________________________________________________________________________________

[[JSP-Howdoesitwork]]
How does it work
----------------

First of all you must have your JSPs (not mandatory but useful). Then
you have to let Pax Web know that you have
jsps by calling the `registerJsps()` method on __WebContainer__. +
 At runtime you have to also deploy the jsp support bundle
*_org.ops4j.pax.web.jsp_* (see installation
instructions bellow) together with Pax
Web. +
 You can find an example of the
link:Examples_5046927.html#Examples-helloworld-jsp[example page].

[[JSP-TagLibs]]
Tag Libs
~~~~~~~~

In order to get your custom tag libs working your TLD files will have to
be reachable in your bundle in ``special'' places:

* all _tld_ files in any jar referenced by your *_Bundle-ClassPath_*
manifest entry
* all _tld_ files in *_WEB-INF_* directory or sub-directory of _WEB-INF_
in your bundle jar

NOTE: Imported packages
are being searched too as of 1.1.2 and 2.0.0. See PAXWEB-86 and
PAXWEB-130. PAX Web JSP’s only scans the META-INF/ directory within each
imported (Import-Package) or required bundle (Require-Bundle), thus
mimicking Jasper’s behaviour when searching JAR files for TLDs.

[[JSP-EnableJSPsupport]]
Enable JSP support
------------------

`public void registerJsps( String[] urlPatterns, HttpContext httpContext )`

Enables jsp support. For more details take a look
link:/wiki/pages/createpage.action?spaceKey=paxweb&title=Pax+Web+-+Jsp&linkCreation=true&fromPageId=5047050[here].

[cols=",",]
|=======================================================================
|urlPatterns |An array of url patterns this jsp support maps to. If
null, a default ``*.jsp'' will be used

|httpContext |The http context for which the jsp support should be
enabled. If null a default http context will be used.

|Throws |UnsupportedOperationException — If jsp support is not available
(optional org.ops4j.pax.web.jsp package is not resolved)
|=======================================================================

[[JSP-DisableJSPsupport]]
Disable JSP support
-------------------

`public void unregisterJsps( HttpContext httpContext )`

Disable jsp support.

[cols=",",]
|=======================================================================
|httpContext |The http context for which the jsp support should be
disabled

|Throws |IllegalArgumentException — If http context is null.

|Throws |UnsupportedOperationException — If jsp support is not available
(optional org.ops4j.pax.web.jsp package is not resolved)
|=======================================================================
