
////

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	 
	    http://www.apache.org/licenses/LICENSE-2.0
	 
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

////

Listeners
=========

[[Listeners-Registereventlisteners]]
Register event listeners
------------------------

*`public void registerEventListener( EventListener listener, HttpContext httpContext )`*

Registers an event listener. Depending on the listener type, the
listener will be notified on different life cycle events. The following
listeners are supported: HttpSessionActivationListener,
HttpSessionAttributeListener, HttpSessionBindingListener,
HttpSessionListener, ServletContextListener,
ServletContextAttributeListener, ServletRequestListener,
ServletRequestAttributeListener. +
 Check out Servlet specification for details on what type of event the
registered listener will be notified.

[[Listeners-Unregistereventlisteners]]
Unregister event listeners
--------------------------

*`public void unregisterEventListener( EventListener listener )`*

Unregisters a previously registered listener.

[cols=",",]
|=======================================================================
|listener |The event listener to be unregistered

|Throws |IllegalArgumentException — if: listener is null the listener is
unknown to the http service (never registered or unregistered before)
|=======================================================================
