[[PaxWeb-Introduction]]
= Introduction

Pax Web 5.x is a servlet container for OSGi web applications. The 5.x release line is currently
experimental and significantly different from the stable 3.x and 4.x release lines.

For a stable OSGi servlet container, please take a look at Pax Web 4.x.

Pax Web 5.x explores some new technologies, and at the same time narrows its scope compared
to the stable releases, with the ultimate goal of merging the 4.x and 5.x release lines, once
the new features of Pax Web 5 have stabilized.

== Functional Goals

  * Implement Web Applications Specification 1.0 (OSGi Enterprise 5, Section 128).
  * Implement Http Service Specification 1.2 (OSGi Enterprise 5, Section 102).
  * Support additional features of Servlet 3.1 Specification.
  * Support JSF, CDI and JSP in Web Application Bundles.
  * Support JSF and JSP libraries in separate bundles.
  * Support Equinox and Felix (OSGi 5.0.0 or higher).
  * Provide Karaf Features (for Apache Karaf 3.0.1 or higher).
  * Java EE 7 API compatibility.


== Design Goals

  * Integrate (an OSGified version of) the Undertow servlet container.
  * Integrate the JSF 2.2 reference implementation (Mojarra 2.2.8 or higher).
  * Simplify OSGi service dependency tracking based on Declarative Services (including DS annotations).
  * Simplify the interaction with Pax CDI.
  
== Non-Goals for the short term

  * Support for Jetty or Tomcat (but still provide a SPI for other web containers)
  * API compatibility with Pax Web <= 4.x.
  
== Long Term Goal

  * Merge with the master branch so that a future Pax Web release will support Jetty, Tomcat and Undertow  
  



