
////

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	 
	    http://www.apache.org/licenses/LICENSE-2.0
	 
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

////

= Servlets

[[Servlets-RegisterservletbyURLpattern]]
== Register servlet by URL pattern

*`public void registerServlet( Servlet servlet, String[] urlPatterns, Dictionary initParams, HttpContext httpContext ) throws ServletException`* +
 Registers a servlet.

[cols=",",]
|=======================================================================
|servlet |The servlet object to register

|urlPatterns |An array of url patterns this servlet maps to. Cannot be
null.

|initParams |Initialization arguments for the servlet or null if there
are none. This argument is used by the servlet’s ServletConfig object.

|httpContext |The HttpContext object for the registered servlet, or null
if a default HttpContext is to be created and used

|Throws |ServletException — if given servlet object has already been
registered

|Throws |IllegalArgumentException — in the following situations: servlet
is null urlPatterns is null or empty
|=======================================================================

To give a name to the registered servlet you can add an element named
_*servlet-name*_ to _initParams_ and as value the servlet name.

NOTE:  starting with 1.1.4
it’s possible to filter init parameters. As shown in
http://wiki.osgi.org/wiki/WebExperience[WebExperience] it’s now possible
to configure the init.parameters for the servlets and filters with the
prefix *_init._* +
 For background info take a look at
http://team.ops4j.org/browse/PAXWEB-349[here]

[[Servlets-Unregisteraservlet]]
== Unregister a servlet

*`public void unregisterServlet( Servlet servlet )`* +
 Unregisters a previously registered servlet.

[cols=",",]
|=======================================================================
|servlet |The servlet to be unregistered

|Throws |IllegalArgumentException — if: servlet is null the servlet is
unknown to Web Container (never registered or unregistered before)
|=======================================================================
