
////

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	 
	    http://www.apache.org/licenses/LICENSE-2.0
	 
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

////

Pax Web User Guide
==================
:toc-title: Pax Web User Guide

The following guides details different aspects of using
Pax Web from the user perspective, where user
means somebody that uses Pax Web.
Details on Pax Web can be found at the link:index.html[overview].

// Push titles down one level
:leveloffset: +1

include::Configuration.adoc[]

include::Http-Service-Extensions.adoc[]

include::Examples.adoc[]

include::WAR-Extender.adoc[]

include::Whiteboard-Extender.adoc[]

include::Installing-using-Karaf-features.adoc[]

include::JSP-Usage.adoc[]

include::Webresources.adoc[]

// Return to normal title levels
:leveloffset: -1
