
////

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	 
	    http://www.apache.org/licenses/LICENSE-2.0
	 
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

////

= WAR Extender

Pax Web Extender WAR is an extender bundle that makes possible to deploy
WAR files into OSGi.

[[WARExtender-Howdoesitwork]]
== How does it work

First you should have a war file compliant with Servlet specs. As the
war file will have to be deployed as a bundle the war file must have the
necessary OSGi manifest headers (take a
look what is required and how you can easily add them). Once you have
this preconditions you just have to deploy your bundle in your preferred
OSGi framework. Of course, what you need more is that pax web extender
war bundle to be installed together
with an http service (preferred Pax Web).

[[WARExtender-Detailedwayofworking]]
== Detailed way of working

Once installed the war extender will watch over the bundles that get
started / stopped. +
 Once your war bundle gets deployed and started, the war extender will
parse your web.xml and registers all elements with http service. If the
http service is link:Pax-Web_3375105.html[Pax Web] then most likely that
you will get a fully working web application. If the http service is a
standard one some of the elements will not be registered as standard
http service only supports servlets and resources. +
 Once your war bundle gets stopped all the prior registered elements
will be unregistered.

[[WARExtender-Benefits]]
== Benefits

* with
https://ops4j1.jira.com/wiki/display/paxurl/War+Protocol[no]/link:OSGi-fy-your-WAR_12060384.html[minimum]
modifications to your war you can deploy it into an osgi framework
* you do not depend on any OSGi api
* you do not have to keep track of http service availability
* you do not have to register/unregister your
servlets/resources/filters/listeners
* easy to use

// Push titles down one level
:leveloffset: +1

include::WAR-Extender-Examples.adoc[]

include::OSGi-fy-your-WAR.adoc[]

include::Supported-Web-Elements.adoc[]

include::WAR-Extender-FAQ.adoc[]

// Return to normal title levels
:leveloffset: -1
