
////

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	 
	    http://www.apache.org/licenses/LICENSE-2.0
	 
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

////

WAR Extender FAQ
================

Is the order the bundles are installed / started important?
-----------------------------------------------------------

No. Http service (Pax Web), war extender or
your war bundle(s) can be installed / uninstalled / started / stopped in
any order. Everything will function as you expect.

What will happen if I stop / uninstall my war?
----------------------------------------------

All the registered elements for the web application corresponding to the
stopped war (servlet context, servlets, resources, filters, listeners)
will be unregistered.

What if I restart it? Or update it?
-----------------------------------

A new web application corresponding to your war will be registered.

What happens if I stop / uninstall the http service?
----------------------------------------------------

All deployed web applications will be unregistered.

What if I restart it?
---------------------

New web applications will be registered for all deployed wars.

What happens if I stop / uninstall the pax war extender?
--------------------------------------------------------

All deployed web applications will be unregistered.

What if I restart it?
---------------------

New web applications will be registered for all deployed wars.

I have a standard war. Can I deploy it into an OSGi framework?
--------------------------------------------------------------

Yes,
OSGi-fy-your-WAR tells you how you can do that.

I do not want / can change the war. Can I still deploy it?
----------------------------------------------------------

Yes, you can do that in a
static or dynamic way.

== Now that I deployed my war, how can I get a service from OSGi Service Registry?

A deployed war is as any OSGi bundle. A bundle accesses the OSGi
framework’s services through the bundle’s __BundleContext__. To enable a
web application to access its _BundleContext_ you must develop a
_BundleActivator_ and add the _Bundle-Activator_ manifest header. This
_BundleActivator_ should store the _BundleContext_ in a location that is
accessible by the application’s servlets, filters or listeners. You can
achieve this by using a static field/method set by your
_BundleActivator_ or store it in a _ServletContext_ attribute.

My application uses JSPs. Are them supported?
---------------------------------------------

Yes, JSPs are supported via Pax Web
Extensions. Take a look at how you can enable JSP
support.

How can I set the servlet context path?
---------------------------------------

Pax Web War extender will use as servlet path by default the symbolic
name of the bundle. If you want to change that you can set the
`Webapp-Context` manifest attribute to the name you want. This attribute
should be set into the manifest (MANIFEST.MF) of the bundle that
contains the web app (same bundle as the one containing the web.xml
file). For example:

----------------------
Web-ContextPath: myApp
----------------------
