
////

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	 
	    http://www.apache.org/licenses/LICENSE-2.0
	 
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

////

= Welcome Files

[[WelcomeFiles-Registerwelcomefiles]]
== Register welcome files

*`public void registerWelcomeFiles( String[] welcomeFiles, boolean redirect, HttpContext httpContext )`*

Registers an ordered list of partial URIs. The purpose of this mechanism
is to allow the deployer to specify an ordered list of partial URIs for
the container to use for appending to URIs when there is a request for a
URI that corresponds to a directory entry in the WAR not mapped to a Web
component. Read Servlet specs for details related to welcome files.

[cols=",",]
|=======================================================================
|welcomeFiles |An array of welcome files paths. Paths must not start or
end with ``/''.

|redirect |True if the client should be rediected to welcome file or
false if forwarded.

|httpContext |The http context these welcome files is for. If null a
default http context will be used.

|Throws |IllegalArgumentException — if: welcome files is null or empty
entries in array are null or empty entries in array start or end with
``/''

|Throws |IllegalStateException — if welcome files are already registered
|=======================================================================

[[WelcomeFiles-Unregisterwelcomefiles]]
== Unregister welcome files

*`public void unregisterWelcomeFiles( HttpContext httpContext )`*

Unregisters previous registered welcome files.

[cols=",",]
|=======================================================================
|httpContext |The http context from which the welcome files should be
unregistered. Cannot be null.

|Throws |IllegalArgumentException — if: no welcome files were registered
before httpContext is null
|=======================================================================
