= pax-web-jsp

== Motivation

There are *four* specifications related roughly to JSP:

* Servlets API (3.1 - JSR 340 and 4.0 - JSR 369)
* JSP API (2.3 - JSR 245)
* JSTL (1.2 - JSR 52)
* EL API (3.0 - JSR 341)

I won't mention JSF (2.3 - JSR 372) and WebSockets (1.1 - JSR 356) here.

While Pax-Web JSP (and Pax-Web in general) assumes Servlets API and EL API to be exported by separate bundles:

* usually official `mvn:javax.servlet/javax.servlet-api/*`
* usually official `mvn:javax.el/javax.el-api/3.0.0`

These will be embedded (and in case of API also exported) within pax-web-jsp itself:

* JSP API
* JSP implementation
* JSTL API
* JSTL implementation
* EL implementation

Servlet API implementation is provided by pax-web-tomcat, pax-web-jetty and pax-web-undertow bundles which play role of _container implementations_.

== Entry points

`pax-web-jsp` doesn't provide any OSGi _entry points_ like bundle activators, SCR components or blueprint descriptors. This bundle's classes have to be used explicitly.

`pax-web-jsp` however provides several JavaEE/JavaSE _entry points_:

* `/META-INF/services/javax.el.ExpressionFactory` with `org.apache.el.ExpressionFactoryImpl` service
* `/META-INF/services/javax.servlet.ServletContainerInitializer` with `org.apache.jasper.servlet.JasperInitializer` service (to check)
* `org.ops4j.pax.web.jsp.JasperInitializer` used directly by pax-web-runtime

(I'll try to make it less confusing and more clear.)

== Information about JSP / JSTL implementations

Taking into account JavaEE 5 - 8 specifications, we have:

* JavaEE 5: JSP 2.1, JSTL 1.2
* JavaEE 6: JSP 2.2, JSTL 1.2
* JavaEE 7: JSP 2.3, JSTL 1.2
* JavaEE 8 (and JakartaEE 8): JSP 2.3, JSTL 1.2

List of Maven artifacts providing APIs and implementations related to Servlets/JSP/EL/JSTL specifications.

* Official JavaEE (recently repackaged under `jakarta` groupId) bundles for APIs (not for implementations!):
** mvn:javax.servlet/javax.servlet-api/3.1.0
+
[options=nowrap]
----
Contains:
    javax.servlet
    javax.servlet.annotation
    javax.servlet.descriptor
    javax.servlet.http

Export-Package:
    javax.servlet;            version="3.1.0"; uses:="javax.servlet.annotation,javax.servlet.descriptor",
    javax.servlet.annotation; version="3.1.0"; uses:="javax.servlet",
    javax.servlet.descriptor; version="3.1.0",
    javax.servlet.http;       version="3.1.0"; uses:="javax.servlet"
Import-Package:
    javax.servlet;            version="3.1.0",
    javax.servlet.annotation; version="3.1.0",
    javax.servlet.descriptor; version="3.1.0",
    javax.servlet.http;       version="3.1.0"
----
** mvn:javax.servlet/javax.servlet-api/4.0.1
+
[options=nowrap]
----
Contains:
    javax.servlet
    javax.servlet.annotation
    javax.servlet.descriptor
    javax.servlet.http

Export-Package:
    javax.servlet;            version="4.0.0"; uses:="javax.servlet.annotation,javax.servlet.descriptor",
    javax.servlet.annotation; version="4.0.0"; uses:="javax.servlet",
    javax.servlet.descriptor; version="4.0.0",
    javax.servlet.http;       version="4.0.0"; uses:="javax.servlet"
Import-Package:
    javax.servlet;            version="4.0.0",
    javax.servlet.annotation; version="4.0.0",
    javax.servlet.descriptor; version="4.0.0",
    javax.servlet.http;       version="4.0.0"
----
** mvn:jakarta.servlet/jakarta.servlet-api/4.0.3
+
[options=nowrap]
----
Contains:
    javax.servlet
    javax.servlet.annotation
    javax.servlet.descriptor
    javax.servlet.http

Export-Package:
    javax.servlet;            version="4.0.0"; uses:="javax.servlet.annotation,javax.servlet.descriptor",
    javax.servlet.annotation; version="4.0.0"; uses:="javax.servlet",
    javax.servlet.descriptor; version="4.0.0",
    javax.servlet.http;       version="4.0.0"; uses:="javax.servlet"
Import-Package:
    javax.servlet,
    javax.servlet.annotation,
    javax.servlet.descriptor
----
** mvn:javax.servlet.jsp/javax.servlet.jsp-api/2.3.3
+
[options=nowrap]
----
Contains:
    javax.servlet.jsp
    javax.servlet.jsp.el
    javax.servlet.jsp.tagext

Export-Package:
    javax.servlet.jsp;        version="2.3.3"; uses:="javax.servlet,javax.el,javax.servlet.jsp.el,javax.servlet.jsp.tagext,javax.servlet.http"
    javax.servlet.jsp.el;     version="2.3.3"; uses:="javax.servlet,javax.el,javax.servlet.jsp,javax.servlet.http",
    javax.servlet.jsp.tagext; version="2.3.3"; uses:="javax.servlet.jsp",
Import-Package:
    javax.el,
    javax.servlet,
    javax.servlet.http,
    javax.servlet.jsp;        version="2.3.3",
    javax.servlet.jsp.el;     version="2.3.3",
    javax.servlet.jsp.tagext; version="2.3.3"
----
** mvn:jakarta.servlet.jsp/jakarta.servlet.jsp-api/2.3.6
+
[options=nowrap]
----
Contains:
    javax.servlet.jsp
    javax.servlet.jsp.el
    javax.servlet.jsp.tagext

Export-Package:
    javax.servlet.jsp;        version="2.3.6"; uses:="javax.servlet,javax.el,javax.servlet.jsp.el,javax.servlet.jsp.tagext,javax.servlet.http",
    javax.servlet.jsp.el;     version="2.3.6"; uses:="javax.servlet,javax.el,javax.servlet.jsp,javax.servlet.http",
    javax.servlet.jsp.tagext; version="2.3.6"; uses:="javax.servlet.jsp"
Import-Package:
    javax.el,
    javax.servlet,
    javax.servlet.http,
    javax.servlet.jsp;        version="2.3.6",
    javax.servlet.jsp.el;     version="2.3.6",
    javax.servlet.jsp.tagext; version="2.3.6"
----
** mvn:javax.servlet.jsp.jstl/javax.servlet.jsp.jstl-api/1.2.2
+
[options=nowrap]
----
Contains:
    javax.servlet.jsp.jstl.core
    javax.servlet.jsp.jstl.fmt
    javax.servlet.jsp.jstl.sql
    javax.servlet.jsp.jstl.tlv

Export-Package:
    javax.servlet.jsp.jstl.core; version="1.2.2"; uses:="javax.servlet,javax.el,javax.servlet.jsp.tagext,javax.servlet.jsp,javax.servlet.http",
    javax.servlet.jsp.jstl.fmt;  version="1.2.2"; uses:="javax.servlet,javax.servlet.jsp.jstl.core,javax.servlet.jsp,javax.servlet.http",
    javax.servlet.jsp.jstl.sql;  version="1.2.2",
    javax.servlet.jsp.jstl.tlv;  version="1.2.2"; uses:="javax.xml.parsers,javax.servlet.jsp.tagext,org.xml.sax.helpers,org.xml.sax"
Import-Package:
    javax.el,
    javax.servlet,
    javax.servlet.http,
    javax.servlet.jsp,
    javax.servlet.jsp.jstl.core; version="1.2.2",
    javax.servlet.jsp.jstl.fmt;  version="1.2.2",
    javax.servlet.jsp.jstl.sql;  version="1.2.2",
    javax.servlet.jsp.jstl.tlv;  version="1.2.2",
    javax.servlet.jsp.tagext,
    javax.xml.parsers,
    org.xml.sax,
    org.xml.sax.helpers
----
** mvn:jakarta.servlet.jsp.jstl/jakarta.servlet.jsp.jstl-api/1.2.7
+
[options=nowrap]
----
Contains:
    javax.servlet.jsp.jstl.core
    javax.servlet.jsp.jstl.fmt
    javax.servlet.jsp.jstl.sql
    javax.servlet.jsp.jstl.tlv

Export-Package:
    javax.servlet.jsp.jstl.core; version="1.2.7";uses:="javax.servlet,javax.servlet.http,javax.servlet.jsp.tagext,javax.el,javax.servlet.jsp",
    javax.servlet.jsp.jstl.fmt;  version="1.2.7";uses:="javax.servlet,javax.servlet.jsp.jstl.core,javax.servlet.http,javax.servlet.jsp",
    javax.servlet.jsp.jstl.sql;  version="1.2.7",
    javax.servlet.jsp.jstl.tlv;  version="1.2.7";uses:="org.xml.sax.helpers,org.xml.sax,javax.servlet.jsp.tagext,javax.xml.parsers"
Import-Package:
    javax.el;                    version="3.0",
    javax.servlet;               version="4.0",
    javax.servlet.http;          version="4.0",
    javax.servlet.jsp,
    javax.servlet.jsp.jstl.core; version="1.2.7",
    javax.servlet.jsp.jstl.fmt;  version="1.2.7",
    javax.servlet.jsp.jstl.sql;  version="1.2.7",
    javax.servlet.jsp.jstl.tlv;  version="1.2.7",
    javax.servlet.jsp.tagext,
    javax.xml.parsers,
    org.xml.sax,
    org.xml.sax.helpers
----
** mvn:javax.el/javax.el-api/3.0.0
+
[options=nowrap]
----
Contains:
    javax.el

Export-Package:
    javax.el; version="3.0.0"
----
** mvn:jakarta.el/jakarta.el-api/3.0.3
+
[options=nowrap]
----
Contains:
    javax.el

Export-Package:
    javax.el; version="3.0.3"
----

* Tomcat 8.5.x/9.0.x:
** mvn:org.apache.tomcat/tomcat-servlet-api - just Servlet API
+
----
javax.servlet
javax.servlet.annotation
javax.servlet.descriptor
javax.servlet.http
javax.servlet.resources
----
** mvn:org.apache.tomcat/tomcat-jsp-api - just JSP API
+
----
javax.servlet.jsp
javax.servlet.jsp.el
javax.servlet.jsp.resources
javax.servlet.jsp.tagext
----
** mvn:org.apache.tomcat/tomcat-el-api - just EL API
+
----
javax.el
----
** mvn:org.apache.tomcat/tomcat-jasper - JSP Impl
+
----
org.apache.jasper.*
----
** mvn:org.apache.tomcat/tomcat-jasper-el - EL Impl
+
----
org.apache.el.*
----
** mvn:org.apache.tomcat.embed/tomcat-embed-core (tomcat JARs + Servlet API)
** mvn:org.apache.tomcat.embed/tomcat-embed-jasper (tomcat-jasper, JSP Impl + JSP API)
** mvn:org.apache.tomcat.embed/tomcat-embed-el (tomcat-jasper-el, EL Impl + EL API)
** mvn:org.apache.taglibs/taglibs-standard-spec - just JSTL API
+
----
Contains:
    javax.servlet.jsp.jstl.core
    javax.servlet.jsp.jstl.fmt
    javax.servlet.jsp.jstl.sql
    javax.servlet.jsp.jstl.tlv

Export-Package:
    javax.servlet.jsp.jstl.core; version="1.2"; uses:="javax.servlet.jsp.tagext,javax.servlet.jsp,javax.servlet,javax.servlet.http,javax.el",
    javax.servlet.jsp.jstl.fmt;  version="1.2"; uses:="javax.servlet,javax.servlet.jsp.jstl.core,javax.servlet.jsp,javax.servlet.http",
    javax.servlet.jsp.jstl.sql;  version="1.2",
    javax.servlet.jsp.jstl.tlv;  version="1.2"; uses:="javax.xml.parsers,javax.servlet.jsp.tagext,org.xml.sax.helpers,org.xml.sax"
Import-Package:
    javax.el,
    javax.servlet,
    javax.servlet.http,
    javax.servlet.jsp,
    javax.servlet.jsp.jstl.core; version="1.2",
    javax.servlet.jsp.jstl.fmt;  version="1.2",
    javax.servlet.jsp.jstl.sql;  version="1.2",
    javax.servlet.jsp.jstl.tlv;  version="1.2",
    javax.servlet.jsp.tagext,
    javax.xml.parsers,
    org.xml.sax,
    org.xml.sax.helpers
----
** mvn:org.apache.taglibs/taglibs-standard-jstlel
+
----
org.apache.taglibs.standard.lang
org.apache.taglibs.standard.tag
org.apache.taglibs.standard.tlv
----
** mvn:org.apache.taglibs/taglibs-standard-compat
+
----
org.apache.taglibs.standard.tag
org.apache.taglibs.standard.tlv
----
** mvn:org.apache.taglibs/taglibs-standard-impl
+
----
org.apache.taglibs.standard.functions
org.apache.taglibs.standard.resources
org.apache.taglibs.standard.tag
org.apache.taglibs.standard.tei
org.apache.taglibs.standard.tlv
org.apache.taglibs.standard.util
----

* Jetty <9.2: Glassfish implementation
** mvn:javax.servlet.jsp/javax.servlet.jsp-api
** mvn:org.glassfish/javax.el
** mvn:org.glassfish.web/javax.servlet.jsp
** mvn:org.glassfish.web/javax.servlet.jsp.jstl

* Jetty >=9.2: Apache (Tomcat) implementation
** mvn:org.mortbay.jasper/apache-jsp - actually shaded mvn:org.apache.tomcat/tomcat-jasper

* Undertow 1.4.x (https://github.com/undertow-io/jastow) - a fork (with Tomcat deps removed) of tomcat-jasper

* Glassfish 5.1 (https://github.com/eclipse-ee4j/glassfish) - it uses many Jakarta-branded JavaEE APIs - mostly from
`org.glassfish.web` groupId
** Servlet API: mvn:javax.servlet/javax.servlet-api/4.0.1 → mvn:jakarta.servlet/jakarta.servlet-api/4.0.2
** JSP API: mvn:javax.servlet.jsp/javax.servlet.jsp-api/2.3.4-SNAPSHOT → mvn:jakarta.servlet.jsp/jakarta.servlet.jsp-api/2.3.4-SNAPSHOT
** JSP Impl: mvn:org.glassfish.web/javax.servlet.jsp/2.3.4 - based on org.apache.tomcat/tomcat-jasper
** JSTL API: mvn:javax.servlet.jsp.jstl/javax.servlet.jsp.jstl-api/1.2.2 → mvn:jakarta.servlet.jsp.jstl/jakarta.servlet.jsp.jstl-api/1.2.7
** JSTL Impl: mvn:org.glassfish.web/javax.servlet.jsp.jstl/1.2.6-SNAPSHOT → mvn:org.glassfish.web/jakarta.servlet.jsp.jstl/1.2.6 - based on org.apache.taglibs/taglibs-standard-impl
** EL API: mvn:javax.el/javax.el-api/3.0.0 → mvn:jakarta.el/jakarta.el-api/3.0.2
** EL Impl: mvn:org.glassfish/javax.el.impl/3.0.1-SNAPSHOT
** EL API + Impl: mvn:org.glassfish/javax.el/3.0.1-SNAPSHOT

About JSTL (https://tomcat.apache.org/taglibs.html):

* Using the -jstlel jar supports JSTL 1.0 EL expressions by using the EL implementation originally defined by JSTL itself.
* Using the -compat jar supports JSTL 1.0 EL expressions by using the container's implementation of EL to take advantage of newer functionality and potential performance improvements in more modern versions.
* -impl jar supports EL expressions as defined in JSP 2.1+ (separate specification - JSR 341)

There are three flavors of JSTL Impl from org.apache.taglibs (see: https://tomcat.apache.org/taglibs.html):

* taglibs-standard-impl
* taglibs-standard-compat (EL 1.0 from Tomcat impl)
* taglibs-standard-jstlel (EL 1.0 from JSTL spec)

taglibs-standard-impl provides different version of TLDs:

 * c.tld (http://java.sun.com/jsp/jstl/core, 1.2)
 * c-1_1.tld (http://java.sun.com/jsp/jstl/core_1_1, 1.1)
 * c-1_0_rt.tld (http://java.sun.com/jstl/core_rt, 1.0 - old, allowing RT expressions in tags, irrelevant now)
 * fmt.tld (http://java.sun.com/jsp/jstl/fmt, 1.1)
 * fmt-1_0_rt.tld (http://java.sun.com/jstl/fmt_rt, 1.0 - old, allowing RT expressions in tags, irrelevant now)
 * sql.tld (http://java.sun.com/jsp/jstl/sql, 1.1)
 * sql-1_0_rt.tld (http://java.sun.com/jstl/sql_rt, 1.0 - old, allowing RT expressions in tags, irrelevant now)
 * x.tld (http://java.sun.com/jsp/jstl/xml, 1.1)
 * x-1_0_rt.tld (http://java.sun.com/jstl/xml_rt, 1.0 - old, allowing RT expressions in tags, irrelevant now)

JSTL descriptors:

* taglibs-standard-compat: c-1_0.tld, fmt-1_0.tld, sql-1_0.tld, x-1_0.tld
* taglibs-standard-jstlel:  c-1_0.tld, fmt-1_0.tld, sql-1_0.tld, x-1_0.tld
* taglibs-standard-impl: c-1_0-rt.tld, c-1_1.tld, c.tld, fmt-1_0-rt.tld, fmt.tld, fn.tld, permittedTaglibs.tld, scriptfree.tld, sql-1_0-rt.tld, sql.tld, x-1_0-rt.tld, x.tld,

== Initialization

The goal of pax-web-jsp from Pax Web perspective is to add "JSP support" to all the "contexts" that need it.

By "JSP support" I don't mean actual Jasper Servlet (`org.apache.jasper.servlet.JspServlet`), but rather registration of `org.apache.jasper.servlet.JasperInitializer` in the context when pax-web-jsp is available.
Original `org.apache.jasper.servlet.JasperInitializer` creates and runs `org.apache.jasper.servlet.TldScanner` which detects `*.tld` files and possibly reads `<taglib>/<listener>/<listener-class>` elements which are then called. For example, one of such listeners is `org.apache.myfaces.webapp.StartupServletContextListener`.

Some well-known `javax.servlet.ServletContainerInitializer` services from `/META-INF/services/javax.servlet.ServletContainerInitializer`:

* `org.apache.jasper.servlet.JasperInitializer`
* `org.apache.tomcat.websocket.server.WsSci`
* `org.apache.myfaces.ee6.MyFacesContainerInitializer`
* `io.undertow.servlet.sse.ServerSentEventSCI`
* `org.springframework.web.SpringServletContainerInitializer` (bridge to `org.springframework.web.WebApplicationInitializer` SPI)
* `org.eclipse.jetty.websocket.server.NativeWebSocketServletContainerInitializer`
* `org.eclipse.jetty.ee8.websocket.javax.server.config.JavaxWebSocketServletContainerInitializer`
* `com.sun.jersey.server.impl.container.servlet.JerseyServletContainerInitializer`

What's most important for Jasper engine is that a JSP servlet requires one context attribute named `org.apache.tomcat.InstanceManager`. This implementation is used to create (and destroy) instances of classes - possibly with support for annotations like `@PostConstruct`. Such instance manager is set by `org.apache.jasper.servlet.JasperInitializer`. This initializer also sets `org.apache.jasper.compiler.TldCache` context attribute.

So, `JasperInitializer` (possibly Pax Web implementation of it) will be used always when JSP servlet is going to be registered inside the context. But such servlet won't be registered by default all the time. I'll be registered implicitly only for WAR/WAB extender when pax-web-jsp is available. In plain HttpService/Whiteboard scenario, such initializer will be initialized only if JSP servlet is added to the context - but it'll have to restart the context, so the lifecycle (like registration of listeners from TLDs) is properly handled.
