= Integration with Keycloak 18

== Background information

https://www.keycloak.org/docs/18.0[Keycloak versions before 19.0] include dedicated Pax Web integration OSGi bundles.

These bundles are:

* org.keycloak/keycloak-pax-web-jetty94
* org.keycloak/keycloak-pax-web-tomcat8
* org.keycloak/keycloak-pax-web-undertow

What's most important that these three bundles provide dedicated `/META-INF/services/org.ops4j.pax.web.service.AuthenticatorService` (an interface from pax-web-api bundle) with these services:

* org.keycloak.adapters.osgi.jetty94.KeycloakAuthenticatorService
* org.keycloak.adapters.osgi.tomcat.KeycloakAuthenticatorService
* org.keycloak.adapters.osgi.undertow.KeycloakAuthenticatorService

These services are used to register/configure runtime-specific authentication service:

* Jetty: `org.eclipse.jetty.security.authentication.LoginAuthenticator` - implemented by `org.keycloak.adapters.jetty.KeycloakJettyAuthenticator`
* Tomcat: `org.apache.catalina.authenticator.FormAuthenticator` - implemented by `org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve`
* Undertow: `io.undertow.servlet.ServletExtension` - implemented by `org.keycloak.adapters.undertow.KeycloakServletExtension`

NOTE: These runtime specific OIDC services use Pax Web service API, however they are called _Fuse Adapters_ - because Red Hat Fuse 7 uses Pax Web Undertow implementation. Historically, JBoss Fuse 6 was using Pax Web Jetty implementation and Keycloak was using Pax Web Jetty specific configuration in org.keycloak/keycloak-osgi-adapter bundle.

== Installation

The Keycloak integration tests can be performed using Apache Karaf 4.4.3.

I've created `org.ops4j.pax.web.samples/whiteboard-security` bundle that uses Whiteboard services to registers:

* '/' and '/pax-web-security' contexts to make them see some extra context (init) parameters
* `org.ops4j.pax.web.service.whiteboard.SecurityConfigurationMapping` - new way (not available in Pax Web 7) to configure login config and security constraints for the above contexts
* `/app/\*`, `/secure/\*`, `/very-secure/\*` and `/logout` servlets
* `/error/\*` servlet to handle 401, 403 and 404 HTTP errors

This Whiteboard sample can be configured using context properties and `org.ops4j.pax.web.itest.container.whiteboard.AbstractWhiteboardSecurityIntegrationTest` uses the sample for `BASIC` authentication

For BASIC whiteboard-security example (just to check Whiteboard-based security configuration):

Before starting Karaf:
----
$ cat <<EOF >>etc/config.properties
paxweb.authMethod = BASIC
paxweb.realmName = default
EOF
----

In Karaf:
----
karaf@root()> feature:install pax-web-http-jetty
karaf@root()> feature:install pax-web-jsp
karaf@root()> feature:install pax-web-whiteboard
karaf@root()> feature:install pax-web-karaf
karaf@root()> install -s mvn:org.ops4j.pax.web.samples/whiteboard-security/8.0.15
----

However the same example can be used to test KEYCLOAK based authentication.

For KEYCLOAK integration, we need to switch the `whiteboard-security` sample to use KEYCLOAK mechanism:
----
$ cat <<EOF >>etc/config.properties
paxweb.authMethod = KEYCLOAK
paxweb.keycloak.resolver = org.keycloak.adapters.osgi.PathBasedKeycloakConfigResolver
EOF
----

And install some Keycloak features. These differ for Jetty, Tomcat and Undertow.

Common features/bundles:
----
karaf@root()> feature:repo-add mvn:org.keycloak/keycloak-osgi-features/18.0.3/xml/features
Adding feature url mvn:org.keycloak/keycloak-osgi-features/18.0.3/xml/features

karaf@root()> feature:install -v keycloak-adapter-core
Adding features: keycloak-adapter-core/[18.0.3,18.0.3]
...
----

Before trying to run the example, we need running Keycloak 18 server:
----
$ bin/add-user-keycloak.sh -u admin
Press ctrl-d (Unix) or ctrl-z (Windows) to exit
Password: admin123
Added 'admin' to '/data/servers/keycloak-18.0.3/standalone/configuration/keycloak-add-user.json', restart server to load user

$ bin/standalone.sh -Djboss.socket.binding.port-offset=100
...
13:34:23,466 INFO  [org.jboss.modules] (main) JBoss Modules version 1.11.0.Final
13:34:23,891 INFO  [org.jboss.msc] (main) JBoss MSC version 1.4.12.Final
13:34:23,900 INFO  [org.jboss.threads] (main) JBoss Threads version 2.4.0.Final
13:34:24,007 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: Keycloak 18.0.3 (WildFly Core 15.0.1.Final) starting
...
13:34:39,620 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:10090
----

Now, the Keycloak console is available at http://127.0.0.1:8180/auth/admin/master/console/#/realms/master.

We need to prepare some configuration:

* separate realm called `paxweb`
* `paxweb-admin` and `paxweb-viewer` roles
* `admin` and `viewer` users (users' passwords must be set)
* `whiteboard-customcontext` _client_ with `http://localhost:8181/pax-web-security/*` _Valid Redirect URIs_
* `whiteboard-rootcontext` _client_ with `http://localhost:8181/*` _Valid Redirect URIs_

Make sure that _Standard Flow Enabled_ is selected for the clients.

After configuring the realm, roles, users and the clients, we can get the configurations and write them to Karaf's:

`etc/whiteboard-customcontext-keycloak.json`:
----
{
  "realm": "paxweb",
  "auth-server-url": "http://127.0.0.1:8180/auth/",
  "ssl-required": "external",
  "resource": "whiteboard-customcontext",
  "public-client": true,
  "confidential-port": 0
}
----

`etc/whiteboard-rootcontext-keycloak.json`:
----
{
  "realm": "paxweb",
  "auth-server-url": "http://127.0.0.1:8180/auth/",
  "ssl-required": "external",
  "resource": "whiteboard-rootcontext",
  "public-client": true,
  "confidential-port": 0
}
----

If the resolver used is `org.keycloak.adapters.osgi.PathBasedKeycloakConfigResolver`, the configuration file for `/pax-web-security` context should be `etc/pax-web-security-keycloak.json`. This option is used to check different types of `org.keycloak.adapters.KeycloakConfigResolver` implementations.

Now, the remaining bundles for Keycloak - Jetty support are:
----
karaf@root()> install mvn:org.keycloak/keycloak-osgi-adapter/18.0.3
Bundle ID: 88
karaf@root()> install mvn:org.keycloak/keycloak-jetty-adapter-spi/18.0.3
Bundle ID: 89
karaf@root()> install mvn:org.keycloak/keycloak-jetty-core/18.0.3
Bundle ID: 90
karaf@root()> install mvn:org.keycloak/keycloak-jetty94-adapter/18.0.3
Bundle ID: 91
karaf@root()> install mvn:org.keycloak/keycloak-pax-web-jetty94/18.0.3
Bundle ID: 92
----

NOTE: `keycloak-pax-http-jetty` feature is disabled in Keycloak OSGi/Karaf features. These bundles are available using `pax-web-jetty-keycloak18` Pax Web feature.

For Tomcat, we need `pax-web-http-tomcat` (instead of `pax-web-http-jetty`) and these Keycloak bundles (again, `keycloak-pax-http-tomcat` is disabled):
----
karaf@root()> install mvn:org.keycloak/keycloak-osgi-adapter/18.0.3
karaf@root()> install mvn:org.keycloak/keycloak-tomcat-core-adapter/18.0.3
karaf@root()> install mvn:org.keycloak/keycloak-tomcat-adapter-spi/18.0.3
karaf@root()> install mvn:org.keycloak/keycloak-tomcat-adapter/18.0.3
karaf@root()> install mvn:org.keycloak/keycloak-pax-web-tomcat8/18.0.3
----

There are however two problems:

1. Tomcat related libraries in Keycloak are not proper OSGi bundles and installing them with `wrap:` is not convenient (as the versions have to be overriden).
2. They use split packages

That's why Pax Web itself ships one proper bundle `mvn:org.ops4j.pax.web/pax-web-tomcat-keycloak18/8.0.15` that:

* re-exports everything needed from Keycloak, which is related to Tomcat
* is a fragment of pax-web-tomcat bundle (so `/META-INF/services/org.ops4j.pax.web.service.AuthenticatorService` can be found).

== Technical details for Jetty integration

When analyzing problems with Keycloak integration, I found that the most problematic part was ... session management.
This is because Whiteboard specification mandates separate sessions for different `org.osgi.service.http.context.ServletContextHelper` service even if they target the same physical target context (like `/`).

In order to fix the problems (for Tomcat and Undertow I was getting endless redirect cycle between Keycloak server and Pax Web runtime), here's the analysis.

First, how session (id) is associated with the incoming request.

`org.eclipse.jetty.server.session.SessionHandler.checkRequestedSessionId()` checks the cookies or `;jsessionid=xxx` URI part. This is done in SessionHandler, so even before SecurityHandler. Next scoped handler of SessionHandler is ServletHandler, however SessionHandler has SecurityHandler set as the handler, so this one is called next.

`org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.requestInitialized()` translates externally-visible JSESSIONID into Whiteboard-scoped session id.

`org.eclipse.jetty.security.SecurityHandler._authenticator` is `org.keycloak.adapters.jetty.KeycloakJettyAuthenticator`.

Initially, `org.eclipse.jetty.server.Request.getAuthentication()` is null, so `org.eclipse.jetty.security.Authenticator.validateRequest()` is called.
Different implementations of `org.eclipse.jetty.server.Authentication` can be used for this initial validation of the request.

* `org.eclipse.jetty.server.Authentication.UNAUTHENTICATED` is sent if Keycloak is not configured correctly
* `org.keycloak.adapters.jetty.Jetty94SessionManager` uses Jetty session handler directly
* `org.keycloak.adapters.PreAuthActionsHandler.handleRequest()` seeems to respond to several URIs like `k_logout` and `k_query_bearer_token` (to check).
* `org.eclipse.jetty.server.Authentication.SEND_SUCCESS` is sent if `PreAuthActionsHandler` was used (to handle one of the `k_*` URIs).

`org.keycloak.adapters.AdapterTokenStore` is taken from: request attribute (`TOKEN_STORE_NOTE`), session (if `org.keycloak.enums.TokenStore.SESSION`) or cookie.

`org.keycloak.adapters.jetty.core.JettyRequestAuthenticator` is created and `org.keycloak.adapters.RequestAuthenticator.authenticate()` is called to prepare `org.keycloak.adapters.spi.AuthChallenge`.
* `org.keycloak.adapters.BearerTokenRequestAuthenticator` (checks `Authorization: Bearer` header and sends `Bearer realm="paxweb"` 401 response if not present).
* `org.keycloak.adapters.QueryParameterTokenRequestAuthenticator` (checks `access_token` query param and sends the same `Bearer` challenge if not present).
* if config allows basic auth, `org.keycloak.adapters.BasicAuthRequestAuthenticator` may be used (checks `Authorization: Basic` header).

`org.keycloak.adapters.OAuthRequestAuthenticator` is created and its `org.keycloak.adapters.OAuthRequestAuthenticator.authenticate()` is called.
If neither `code` nor `error` request params are present, redirect is sent:
* `state` is new random UUID
* `login_hint`, `kc_idp_hint`, `scope`, `prompt`, `max_age`, `ui_locales` query params are stripped from current request
* `response_type=code`
* `client_id=whiteboard_rootcontext` (from Keycloak _client_)
* `redirect_uri=<encoded original URI>`
* `state=<UUID>`
* `login=true`
* `scope=openid`
* result is redirect to `http://127.0.0.1:8180/auth/realms/paxweb/protocol/openid-connect/auth?response_type=code&client_id=whiteboard-rootcontext&redirect_uri=http%3A%2F%2Flocalhost%3A8181%2Fsecure%2Finfo&state=557b6fc8-dba1-4936-ab63-eb44b1b630aa&login=true&scope=openid`

`validateRequest()` calls `org.keycloak.adapters.spi.AuthChallenge.challenge()` on the established challenge (initially it should be a redirect from `OAuthRequestAuthenticator`).

First important session interaction is that challenge execution for OAuth2 redirect saves the "request" using `org.keycloak.adapters.spi.AdapterSessionStore.saveRequest()`. It calls `javax.servlet.http.HttpServletRequest.getSession()` which creates the session if one doesn't exist.
Whiteboard suffix is already added to new session ID: `node0u7q11d3tgney8tbous2ou9bu0~ROOT#default` and visible in extended ID: `node0u7q11d3tgney8tbous2ou9bu0~ROOT#default.node0`.

`org.eclipse.jetty.server.session.SessionHandler.getSessionCookie()` is called after creating a session.

Saving KC request in the session means this set of attributes:
* `org.eclipse.jetty.security.form_URI`
* `org.eclipse.jetty.security.HTTP_METHOD`

Finally these are send in the redirect:
* HTTP 302
* Location pointing to auth URI
* `Set-Cookie: OAuth_Token_Request_State=<UUID>` (for the generated previously `state`).

After logging in in Keycloak UI, we're redirected again to original URI with additional parameters:
* state=f8f6f1d6-2013-49dd-970c-45baae4256a1
* session_state=7038ea65-45fd-4bdd-8661-4a6c431c20af
* code=ba54ac1d-bd36-4541-b446-ecd04599a9ff.7038ea65-45fd-4bdd-8661-4a6c431c20af.066beaab-aaa6-4fe4-93d9-766dc2ee30a8

This time, `org.keycloak.adapters.OAuthRequestAuthenticator.authenticate()` actually gets the code.
`OAuth_Token_Request_State` cookie is consulted and compared with `state` parameter.

For `org.keycloak.enums.TokenStore.SESSION` (if not turned off), `org.eclipse.jetty.server.Request.changeSessionId()` is called, existing session gets new ID and new `Set-Cookie` will be generated for the response.

`org.keycloak.adapters.ServerRequest.invokeAccessCodeToToken()` is called with these POST data:
* `grant_type=authorization_code`
* `code=<code>` from the 2nd redirect
* `redirect_uri=<URI>`
* `client_session_state=<new session ID>"` (this is full Whiteboard ID! `node0756nws6o4t2p1sxt448feejy71~ROOT#default`)
* `client_session_host=<host>`

Target URL is `http://127.0.0.1:8180/auth/realms/paxweb/protocol/openid-connect/token`.
* `client_id=whiteboard-rootcontext` is added if `org.keycloak.adapters.KeycloakDeployment.publicClient == true`

JSON similar to this one should be returned:
----
{
  "access_token": "<token>",
  "expires_in": 300,
  "refresh_expires_in": 1800,
  "refresh_token": "<token>",
  "token_type": "Bearer",
  "id_token": "<token>",
  "not-before-policy": 1676307413,
  "session_state": "7038ea65-45fd-4bdd-8661-4a6c431c20af",
  "scope": "openid profile email"
}
----

`org.keycloak.adapters.spi.AuthOutcome.AUTHENTICATED` is returned from `OAuthRequestAuthenticator.
`org.keycloak.KeycloakPrincipal` is created.
`org.keycloak.KeycloakSecurityContext` request attribute is set with an instance of `org.keycloak.adapters.RefreshableKeycloakSecurityContext`.
`org.keycloak.KeycloakSecurityContext` session attribute is also set.

== Technical details for Tomcat integration
